load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "application",
    srcs = [
        "account.go",
        "auth.go",
        "blockchain.go",
        "bond.go",
        "cash_transaction.go",
        "customer.go",
        "errors.go",
        "instruments.go",
        "market_data.go",
        "option.go",
        "order.go",
        "payment.go",
        "portfolio.go",
        "ports.go",
        "position.go",
        "quotes.go",
        "settlement.go",
        "trade.go",
        "watchlist.go",
        "watchlist_item.go",
    ],
    importpath = "finpulse/server-go/internal/application",
    visibility = ["//apps/server-go:__subpackages__"],
    deps = [
        "//apps/server-go/internal/domain",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "application_test",
    srcs = [
        "account_test.go",
        "auth_test.go",
        "blockchain_test.go",
        "bond_test.go",
        "cash_transaction_test.go",
        "customer_test.go",
        "instruments_test.go",
        "market_data_test.go",
        "option_test.go",
        "order_test.go",
        "payment_test.go",
        "portfolio_test.go",
        "position_test.go",
        "quotes_test.go",
        "settlement_test.go",
        "trade_test.go",
        "watchlist_item_test.go",
        "watchlist_test.go",
    ],
    embed = [":application"],
    deps = ["//apps/server-go/internal/domain"],
)
